#DATADICTION

Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere



## BASIC PYTHON


Question-Write a Python function named slope_of_cubic that calculates the slope of a cubic polynomial based on user input. The function should:
1. Accepts two arguments:

* A tuple containing 4 real numbers which are the coefficients of the cubic term, quadratic term, linear term, and constant term respectively.

* A real number which is the value of x at which the slope has to be calculated.

2. Returns the slope of the cubic polynomial at the given value of x.

In [2]:
def slope_of_cubic(tu, x):
  return (3*tu[0]*(x**2) + 2*tu[1]*x + tu[2])

##NumPy (Numerical Python)
###Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of ndarray

In [1]:
import numpy as np

In [ ]:
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it


In [4]:
# Write a NumPy function to create an array with random values of shape [3,4]

np.random.randint(0,11, size=(3,4))

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]

np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
np.arange(0, 10, 1)
# Hint : Use np.arange or np.linspace

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Basic array operations
- algebraic operations
- logical operations

In [21]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [8]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
a + b

array([[ 7, 22, 26],
       [99, 40, 82],
       [62, 56, 80]])

In [10]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
np.sum(a, axis = 0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
np.sum(a, axis = 1)

array([10, 13, 14])

In [13]:
# Write a NumPy function to reverse the array 'a'
np.flip(a)
# Write a NumPy function to reverse the array 'a' along axis=0
np.flip(a, axis=0)
# Write a NumPy function to reverse the array 'a' along axis=1
np.flip(a, axis = 1)

array([[ 8,  6, -4],
       [ 1,  3,  9],
       [ 5,  8,  1]])

### Sorting and concatenation
- sort arrays
- join multiple arrays

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [18]:
# Write a NumPy function to sort the array 'a'
a.sort()
# Write a NumPy function to sort the array 'a' along axis=0
a.sort(axis = 0)
# Write a NumPy function to sort the array 'a' along axis=1
a.sort(axis = 1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
a.sort(axis = 0)
np.flip(a, axis = 0)

array([[ 1,  6,  9],
       [ 1,  5,  8],
       [-4,  3,  8]])

In [22]:
# Write a NumPy function to argsort the array along axis=0
np.argsort(a, axis = 0)
# Write a NumPy function to argsort the array along axis=1
np.argsort(a, axis = 1)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1]])

In [33]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
np.concatenate((a,b))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
np.concatenate((a, b), axis = 0)
# Note: You can do the same function using stacking, discover and try that :)
np.stack((a,b), axis =0)

array([[[-4,  6,  8],
        [ 9,  3,  1],
        [ 1,  8,  5]],

       [[11, 16, 18],
        [90, 37, 81],
        [61, 48, 75]]])

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array


In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [44]:
# Write a NumPy function to get the Number of dimensions
np.ndim(a)
# Write a NumPy function to get the Shape of the array
np.shape(a)
# Write a NumPy function to get the Size of the array
np.size(a)

2

In [40]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
np.reshape(a, newshape=(1,9))


array([[-4,  6,  8,  9,  3,  1,  1,  8,  5]])

In [48]:
# Write a NumPy function to add a new axis to the array 'a'
np.expand_dims(a, axis=0)
# Note : Show atleast two different ways of doing this

array([[[-4,  6,  8],
        [ 9,  3,  1],
        [ 1,  8,  5]]])

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [49]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [59]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
a[2,2]
a[:2, 1]

array([6, 3])

In [57]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
a[a>4]
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
a[(a>4) & (a %2== 0)]

array([6, 8])

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [60]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
c = a.copy() + 1
c

array([[5, 7, 1],
       [1, 4, 2],
       [2, 9, 6]])

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.


#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [62]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
import pandas as pd


In [71]:
# Write a Pandas function to drop rows that contain a missing value.
df = pd.DataFrame(iris_2d)
df.dropna()
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [65]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
df.mean()
df.median()
df.std()

0    0.828066
1    0.433594
2    1.764420
3    0.763161
dtype: float64

In [70]:
# Write a Pandas function to find the correlation between the first two columns.
df.iloc[:,0].corr(df.iloc[:,1])
df.columns = ['col1', 'col2', 'col3', 'col4']

np.float64(-0.10936924995064937)

In [77]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
df["Volume"] = (np.pi * df['col1'] * (df['col2']**2))/3
df
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

col1  col2  col3  col4     Volume
0     5.1   3.5   1.4   0.2  65.423667
1     4.9   3.0   1.4   0.2  46.181412
2     4.7   3.2   1.3   0.2  50.399524
3     4.6   3.1   1.5   0.2  46.292415
4     5.0   3.6   1.4   0.2  67.858401
..    ...   ...   ...   ...        ...
145   6.7   3.0   5.2   2.3  63.146012
146   6.3   2.5   5.0   1.9  41.233404
147   6.5   3.0   5.2   2.0  61.261057
148   6.2   3.4   5.4   2.3  75.054743
149   5.9   3.0   5.1   1.8  55.606190

[150 rows x 5 columns]

### Miscellaneous

Q1 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

> Add blockquote



In [92]:
x = np.random.randint(1, 10, size = (2,5))
print(x)
print(x.min(axis = 1))
print(x.argmin(axis = 1))
print('\n')
print(x.max(axis = 1))
print(x.argmax(axis = 1))

[[6 9 2 9 6]
 [9 4 9 4 3]]
[2 3]
[2 4]


[9 9]
[1 0]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [125]:
x = [1,2,3,4,5,6,7,8,9]
a = []
b = []
c = []
for i in range(9):
  j = np.random.randint(0, len(x))
  if i < 4:
    a.append(x[j])
    x.remove(x[j])
  elif i < 6:
    b.append(x[j])
    x.remove(x[j])
  else:
    c.append(x[j])
    x.remove(x[j])

### PANDAS

Run the following cell before proceeding further


In [93]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q3- Write a Pandas function to find the count of unique species.

In [104]:
df = pd.DataFrame(iris)
df.columns = names
df = df.drop_duplicates()
len(df)
df.head()


sepallength sepalwidth petallength petalwidth         species
0      b'5.1'     b'3.5'      b'1.4'     b'0.2'  b'Iris-setosa'
1      b'4.9'     b'3.0'      b'1.4'     b'0.2'  b'Iris-setosa'
2      b'4.7'     b'3.2'      b'1.3'     b'0.2'  b'Iris-setosa'
3      b'4.6'     b'3.1'      b'1.5'     b'0.2'  b'Iris-setosa'
4      b'5.0'     b'3.6'      b'1.4'     b'0.2'  b'Iris-setosa'

# Q4 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [110]:
df['petallength'] = df['petallength'].astype(np.float128)
df['sepallength'] = df['sepallength'].astype(np.float128)
df['petalwidth'] = df['petalwidth'].astype(np.float128)
df['sepalwidth'] = df['sepalwidth'].astype(np.float128)
def func(x):
  if x < 3.0:
    return 'small'
  elif x < 5.0:
    return 'medium'
  else:
    return 'large'
df['size'] = df['petallength'].apply(func)
df

sepallength  sepalwidth  petallength  petalwidth            species  \
0            5.1         3.5          1.4         0.2     b'Iris-setosa'   
1            4.9         3.0          1.4         0.2     b'Iris-setosa'   
2            4.7         3.2          1.3         0.2     b'Iris-setosa'   
3            4.6         3.1          1.5         0.2     b'Iris-setosa'   
4            5.0         3.6          1.4         0.2     b'Iris-setosa'   
..           ...         ...          ...         ...                ...   
145          6.7         3.0          5.2         2.3  b'Iris-virginica'   
146          6.3         2.5          5.0         1.9  b'Iris-virginica'   
147          6.5         3.0          5.2         2.0  b'Iris-virginica'   
148          6.2         3.4          5.4         2.3  b'Iris-virginica'   
149          5.9         3.0          5.1         1.8  b'Iris-virginica'   

      size  
0    small  
1    small  
2    small  
3    small  
4    small  
..     ...  
145  large  
146  large  
147  large  
148  large  
149  large  

[147 rows x 6 columns]

Q5 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [111]:
df['petallength'].mode()

0    1.4
1    1.5
Name: petallength, dtype: float128