#DATADICTION

Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere



## BASIC PYTHON


Question-Write a Python function named slope_of_cubic that calculates the slope of a cubic polynomial based on user input. The function should:
1. Accepts two arguments:

* A tuple containing 4 real numbers which are the coefficients of the cubic term, quadratic term, linear term, and constant term respectively.

* A real number which is the value of x at which the slope has to be calculated.

2. Returns the slope of the cubic polynomial at the given value of x.

In [ ]:
def slope_of_a_cubic(coefficients, x):
  a, b, c = coefficients
  slope = 3*a*x*x + 2*b*x + c
  print(slope)

##NumPy (Numerical Python)
###Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of ndarray

In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it

a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]

random = np.random.random((3,4))

print(random)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]

zero_arr = np.zeros((3,4))
print(zero_arr)

[[0.39580751 0.3374287  0.29441803 0.57861912]
 [0.54665723 0.60701773 0.47345761 0.43635834]
 [0.96255137 0.36241089 0.77617586 0.04557045]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace

spaced = np.arange(0, 11, 5)
print(spaced)

[ 0  5 10]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
add = a + b
subtract = a - b
multiply = a*b
divide = a/b

print(add)
print(subtract)
print(multiply)
print(divide)


[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
sum0 = np.sum(a, axis=0)
print(sum0)

# Write a NumPy function to get the sum of the array 'a' along axis=1
sum1 = np.sum(a, axis=1)
print(sum1)

[ 6 17 14]
[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'
reverse_a = a[: : -1]
print(reverse_a)

# Write a NumPy function to reverse the array 'a' along axis=0
rev0 = np.flip(a, axis = 0)
print(rev0)

# Write a NumPy function to reverse the array 'a' along axis=1
rev1 = np.flip(a, axis = 1)
print(rev1)


[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
sorta = np.sort(a)
print(sorta)

# Write a NumPy function to sort the array 'a' along axis=0
sort0 = np.sort(a, axis=0)
print(sort0)

# Write a NumPy function to sort the array 'a' along axis=1
sort1 = np.sort(a, axis=1)
print(sort1)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
descending_sort0 = np.sort(a, axis=0)[::-1]
print(descending_sort0)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
argsort0 = np.argsort(a, axis=0)
print(argsort0)

# Write a NumPy function to argsort the array along axis=1
argsort1 = np.argsort(a, axis=1)
print(argsort1)


[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
concat = np.concatenate((a,b))
print(concat)

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
concat0 = np.concatenate((a,b), axis=0)
print(concat0)

# Note: You can do the same function using stacking, discover and try that :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array


In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
from numpy._core import shape_base
# Write a NumPy function to get the Number of dimensions
dimensions = a.ndim
print(dimensions)

# Write a NumPy function to get the Shape of the array
shape = a.shape
print(shape)

# Write a NumPy function to get the Size of the array
size = a.size
print(size)

2
(3, 3)
9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
reshape = a.reshape(1,9)
print(reshape)

[[-4  6  8  9  3  1  1  8  5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this

new = np.expand_dims(a, axis=0)
print(new)

new = np.expand_dims(a, axis=1)
print(new)

[[[-4  6  8]
  [ 9  3  1]
  [ 1  8  5]]]
[[[-4  6  8]]

 [[ 9  3  1]]

 [[ 1  8  5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range



In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[a>4])

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a>4) & (a%2==0)])

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
copy = np.copy(a)
print(copy)

increased_array = a+1
print(increased_array)

[[4 6 0]
 [0 3 1]
 [1 8 5]]
[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.


#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd

df = pd.DataFrame(iris_2d)

drop_r = df.dropna()
drop_r

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.

col3_mean = df[2].mean()
col3_median = df[2].median()
col3_std = df[2].std()

col3_mean, col3_median, col3_std


(np.float64(3.758666666666666), 4.35, 1.7644204199522617)

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.

correlation = df[0].corr(df[1])
correlation

np.float64(-0.10936924995064937)

In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

import numpy as np

df['volume'] = (np.pi * df[2] * (df[0] ** 2)) / 3
df

0    1    2    3      volume
0    5.1  3.5  1.4  0.2   38.132652
1    4.9  3.0  1.4  0.2   35.200498
2    4.7  3.2  1.3  0.2   30.072372
3    4.6  3.1  1.5  0.2   33.238050
4    5.0  3.6  1.4  0.2   36.651914
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.445230
146  6.3  2.5  5.0  1.9  207.816354
147  6.5  3.0  5.2  2.0  230.069302
148  6.2  3.4  5.4  2.3  217.373079
149  5.9  3.0  5.1  1.8  185.910028

[150 rows x 5 columns]

### Miscellaneous

Q1 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.randint(0,10,(2,5))
print(x)

max_val = np.max(x, axis=1)
min_val = np.min(x, axis=1)

max_idx = np.argmax(x, axis=1)
min_idx = np.argmin(x, axis=1)

print("Maximum values:", max_val)
print("Minimum values:", min_val)
print("Indices of maximum values", max_idx)
print("Indices of minimum values", min_idx)

[[3 2 7 0 0]
 [1 2 4 1 3]]
Maximum values: [7 4]
Minimum values: [0 1]
Indices of maximum values [2 2]
Indices of minimum values [3 0]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9,10])


x1 = x[:4]
x2 = x[4:6]
x3 = x[6:]

print(x1)
print(x2)
print(x3)


[1 2 3 4]
[5 6]
[ 7  8  9 10]


### PANDAS

Run the following cell before proceeding further


In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q3- Write a Pandas function to find the count of unique species.

In [ ]:
def count_unique_species(df):
  return df['species'].nunique()

  df = pd.DataFrame(iris, columns=names)
  count = count_unique_species(df)
  print(count)

# Q4 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
def petallength(df):
  bins = [0,3,5,np.inf]
  labels = ['small', 'medium', 'large']
  df['petallength'] = pd.cut(df[2],bins=bins, labels=labels)
  return df

Q5 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
def petalfreq(df):
  return df.iloc[:,2].mode()[0]